### ISSUE TITLE
Instructions unclear on where to put config

### ISSUE THREAD

**Issue by mokshmridul** [blankhaus/klipper-filter_monitor#1]
Hi,

I have been able to install the plugin, however, putting 

```
[filter_monitor bed_filter]
fan: "fan_generic bed_fans"
```

or

```
[filter_monitor bed_filter]
fan: 'fan_generic bed_fans' # e.g fan_generic bed_filter, heater_generic heated_chamber, etc
max_runtime_hours: 50 # Defaults to 50 hours
max_days: 30 # Defaults to 30 days
interval: 30 # Defaults to 30 seconds
expiry_gcode: # Executed when filter meets threshold condition
path: ~/printer_data/config/plugins/filter_monitor # Folder where filter data is stored
```
in the `printer.cfg' causes the following errors in mainsail / klipper:

![image](https://github.com/user-attachments/assets/5454f75d-ad7c-4dcb-a193-46590a91bd71)

Note: My nevermore has the following config in `printer.cfg`

```
[fan_generic Nevermore]
# Link: https://github.com/top-gun/Nevermore-Klipper
pin: PB7
```

**Comment by mut3xx** [comment]
Hi,

No worries! 

Just set your "fan" parameter to "fan_generic Nevermore" like so:

[filter_monitor bed_filter]
fan: "fan_generic Nevermore"

Let me know if that works for you!

**Comment by mokshmridul** [comment]
Gave that a shot, and still facing the same error message.

**Comment by mut3xx** [comment]
Would you be ok sharing your printer.cfg with me?

**Comment by mokshmridul** [comment]
Sure, should i share it here? or somewhere else?

**Comment by mut3xx** [comment]
Here is fine with me if you're comfortable with it.

**Comment by mokshmridul** [comment]
Here is the file. Ive called it printer.txt, because github is not letting me upload .cfg files. 
[printer.txt](https://github.com/user-attachments/files/16716160/printer.txt)

**Comment by luco85** [comment]
Same issue for me and same setup with nevermore fan as generic

**Comment by mut3xx** [comment]
The quotes need to be omitted from the fan config parameter. I'll update the docs. 

Set your config as follows:

```
[filter_monitor bed_filter]
fan: fan_generic Nevermore
```

Let me know if that works for the both of you!

**Comment by mokshmridul** [comment]
Hey,
just tried this as well, and its still not working. Same error.

**Comment by mokshmridul** [comment]
New error though:
![image](https://github.com/user-attachments/assets/09ed2e70-1d7e-4700-8f5b-0c5fdcc82093)

**Comment by mut3xx** [comment]
Can you please post your relevant config section for your nevermore and the plugin here? Have you also restarted your firmware?

I was able to replicate using your exact config and resolved using my suggestions above.

**Comment by mut3xx** [comment]
The default data path is ~/printer_data/config/plugins/filter_monitor or you can specify another. However, you will need to make sure that folder exists as per the error message.

**Comment by mokshmridul** [comment]
Got it working after correcting the `path: ~/printer_data/config/filter_monitor` and making a folder called `filter_monitor`. Closing this issue. 

Thanks for the quick help.
